import java.util.Scanner;

public class email_input {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Write your email");
        String email = sc.nextLine();
        String username = "";
        for(int i=0; i<email.length(); i++) {
            if(email.charAt(i) == '@') {
                break;
            } else {
                username += email.charAt(i);
            }
        }

        System.out.println("Your username generated by our AI: ");
        System.out.println(username);
    }
}
